name: Daily Commit

on:
  schedule:
    - cron: "0 18 * * *"  # Runs daily at 11:30 PM IST (18 UTC)
  workflow_dispatch:      # Allows manual run

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make daily change
        run: |
          echo "Updated on: $(date)" >> daily.txt

      - name: Commit changes
        run: |
          git config --global user.email "svivekpratap784@gmail.com"
          git config --global user.name "Vivek-pratap-singh"
          git add .
          git commit -m "Daily automated commit" || echo "No changes to commit"

      - name: Push changes
        run: git push
